# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Laurel Hill Nursery School &amp; Pre-K
email: info@laurelhill.org
address: 401 Euclid Avenue San Francisco, CA 94118 
number: "(415) 751-8784"

description: > # this means to ignore newlines until "baseurl:"


  © 2011-2015 Laurel Hill Nursery School
 
  
  
baseurl: "/lhns" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site


# Build settings
markdown: kramdown

collections:
 about_us:
  output: true
 programs:
  output: true
 admissions:
  output: true
 contact:
  output: true



